Add checks to ensure distance is strictly less than half of kernel width
flatironinstitute/cufinufft pull request #113
Opened 2021-07-07 19:26 UTC by MelodyShih

This is related to #112 .

The error happens when nonuniform points lie on the fine grid. 
The distance between the point and the grid point are exactly `kernelwidth/2` and cause 
`exp(es_beta * (sqrt(1.0 - es_c*x*x)))` evaluates to `nan`. 

I added checks to enforce this does not happen.

2021-07-08 15:22 UTC, ahbarnett commented
Yes, this was needed in FINUFFT too, when the plain exp(sqrt(..)) kernel used:
https://github.com/flatironinstitute/finufft/blob/adcb1d25aa8f3b26aed1956a9dccc12bd8a78eea/src/spreadinterp.cpp#L639
With the vectorized Horner eval, there are no NaNs, so no such check was needed.

Note that your PR has an awful lot of repetition of the check. Could it be rationalized so that the kernel eval and associated check is done in one place only?

You might want to check that tweaks to rounding and wrapping in FINUFFT over the last year have been brought into cuFINUFFT. I can list commits if you need, but have a look in spreadinterp.cpp, basically.
Best, Alex

2021-07-08 15:26 UTC, ahbarnett commented on src/2d/spreadinterp2d.cu
> +			FLT kervalue2 = disy<ns/2.0 ? evaluate_kernel(disy, es_c, es_beta):0;
Hi, while this works, I suggest you incorporate this check into evaluate_kernel. This requires adding an extra arg, ns. But then you won't have the same check repeated 10 times as below, which is much harder to maintain...

2021-07-08 15:27 UTC, ahbarnett requested changes
Hi Melody - sorry, if you have time, could you tweak this as in my code comment, for cleaner non-repetitive code?  Thanks, Alex

2021-07-08 15:37 UTC, MelodyShih commented
Hi Alex, sure, sounds better to do what you suggest. I will update with a new commit. Best regards, Melody

2021-07-09 13:46 UTC, ahbarnett approved these changes

2021-07-09 17:12 UTC, merged